<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RemoveFromCart</name>
   <tag></tag>
   <elementGuidId>d72fc947-0b25-4bee-9264-05400834e665</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/main/div/div/div/div/div[3]/div/div[1]/div/div[2]/div[2]/div/div[1]/div/div[1]/div[2]/div[1]/div/div/div[8]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
