<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MotorOne</name>
   <tag></tag>
   <elementGuidId>5a4479c7-9005-4749-907f-fa395e13f3fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;wrapper&quot;]/main/div/div[2]/div/div[2]/div[1]/div/div/div[2]/div/div[3]/div/div[1]/table/tbody[1]/tr[2]/td[1]/div/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
